/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dj;

import org.beryx.textio.TextIO;
import org.beryx.textio.TextIoFactory;
import org.beryx.textio.TextTerminal;

public class App {
    public static void main(String[] args) {
        App app = new App();

        TextIO textIO = TextIoFactory.getTextIO();
        String name = textIO.newStringInputReader()
                .withDefaultValue(app.getDefaultName())
                .read("Username");

        TextTerminal terminal = textIO.getTextTerminal();
        terminal.printf("\nHello, %s!\n", name);
    }

    public String getDefaultName() {
        return "world";
    }
}
